### ISSUE TITLE
Import CATcher labels for WATcher

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#38] opened 2022-07-30 08:53 UTC
WATcher should use the same issue labels as CATcher on this repository.

**Comment by Echomo-Xinyu** [comment] 2023-02-06 05:14
Hi @gycgabriel, may I check whether the intention of the issue is to manually add the issue labels such as "aspect.Process", "s.toDiscuss" to the WATcher repository? If so, do you think it is finished so that we may close the issue now?

**Comment by gycgabriel** [comment] 2023-02-08 09:59
Hi @Echomo-Xinyu, yes that is the intention because afaik there isn't an automated way to do it currently without handing over repo write permissions to third party software

A quick look at the label counts for WATcher: 27, for CATcher: 38, I think we are still missing a few.

**Comment by Echomo-Xinyu** [comment] 2023-02-11 11:47
Ok, I have by now added all the labels from CATcher already.

**Closed by Echomo-Xinyu** 2023-02-11 11:47 UTC
Labels: enhancement, good first issue, difficulty.Moderate
