### ISSUE TITLE
Remove scrollbar on Labels Filter bar when not needed

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#17] opened 2022-07-11 02:31 UTC
**Describe the bug**
The labels filter bar shows a scrollbar even when there is nothing to scroll below.
I've tried resizing the html components surrounding it, but the scrollbar is displayed even when set to auto.

**Expected behavior**
The scrollbar should only be displayed if there are so many labels selected to be filtered that it overflows.

**Screenshots**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/77230723/178177462-5206ff67-8be6-4275-871e-d93c777fb394.png">

**Comment by seetohjinwei** [comment] 2023-07-01 07:39
Hi! I think this issue might have been fixed already, as I cannot reproduce it.

However, I noticed that

- a repository with no issues still displays a fixed height container
- a repository with many issues is scrollable, but there is no scroll bar
  - this seems to be intentional based on the CSS, but I feel like this might lead to the user being unaware that the container is scrollable

## Currently

Repository with many labels:

![image](https://github.com/CATcher-org/WATcher/assets/47915290/d2dfcbf8-96ca-4d42-abc1-80e7929b87b9)

Repository with no labels:

![image](https://github.com/CATcher-org/WATcher/assets/47915290/afa97ebf-f958-4116-8e79-03e90d816338)

## Proposed Change

- Change `height: 400px` to `max-height: 400px`
- Allow the scrollbar to be visible when there is content to be scrolled

![image](https://github.com/CATcher-org/WATcher/assets/47915290/0106e472-4d84-4b60-bc3f-05fdd5610bd8)

**Comment by Eclipse-Dominator** [comment] 2023-07-02 15:56
Sounds good, lets make this in a separate issue and close this one

**Comment by NereusWB922** [comment] 2024-01-20 09:19
Issue solved by #163.

**Closed by NereusWB922** 2024-01-20 09:19 UTC
Labels: aspect-UIX, difficulty.Moderate
