### ISSUE TITLE
Pressing 'back' clears all issues

### ISSUE THREAD

**Issue by kkangs0226** [CATcher-org/WATcher#128] opened 2023-04-10 08:19 UTC
## Summary

Pressing 'back' after starting a session reloads same repository, but does not show any issues. 

## Steps to reproduce: 
1. Log into a session 
2. Press back on your browser
3. Same repository, however the issues do not load at all. 

Likely related to #65

**Comment by Eclipse-Dominator** [comment] 2023-04-10 10:41
The reset is actually caused by the reset in initialization of issueService here
```typescript
 private initialize() {
    this.checkIfValidRepository().subscribe((isValidRepository) => {
      if (!isValidRepository) {
        throw new Error('Invalid repository name. Please provide repository name in the format Org/Repository.');
      }
    });

    // Fetch assignees
    this.assignees = [];

    this.githubService.getUsersAssignable().subscribe((x) => (this.assignees = x));

    // Fetch issues
    this.issueService.reset(false); <=====
    this.issueService.reloadAllIssues();
```

This line line causes issueService to reload everytime the issueviewer is regenerated. This can be resolved by moving this line to the here
```typescript
  constructor(
    public phaseService: PhaseService,
    public githubService: GithubService,
    public issueService: IssueService,
    public milestoneService: MilestoneService,
    private logger: LoggingService
  ) {
    this.repoChangeSubscription = this.phaseService.repoChanged$.subscribe((newRepo) => this.initialize());
  }
```

**Closed** 2023-06-30 17:57 UTC
Labels: category.Bug
