### ISSUE TITLE
Unable to launch WATcher from local browser

### ISSUE THREAD

**Issue by Echomo-Xinyu** [CATcher-org/WATcher#54] opened 2023-01-14 04:16 UTC
**Describe the bug**
After setting up the environment, when running `npm run ng:serve:web`, the application will be stuck on "Loading..." page and an exception is thrown as below:
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/25452497/212450108-41482afb-418e-42d7-b954-1559ab269843.png">

**To Reproduce**
1. set up the environment with `npm install`
2. run `npm run ng:serve:web`
3. open "http://localhost:4200/" in browser
4. see the page as screenshot above

**Expected behavior**
The application should display certain content.

**Screenshots**
as above
The specific log is:
```log
browser.js:20 Uncaught ReferenceError: global is not defined
    at ./node_modules/node-fetch/browser.js (browser.js:20:1)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/@octokit/request/dist-web/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/@octokit/rest/lib/constructor.js (constructor.js:3:21)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/@octokit/rest/lib/factory.js (factory.js:3:17)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/@octokit/rest/lib/core.js (core.js:1:17)
    at __webpack_require__ (bootstrap:79:1)
```

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 12.5 Monterey

**Comment by kkangs0226** [comment] 2023-01-14 09:01
Duplicate of #53 

Issue seems to be with Angular not providing a shim for ```global``` while octokit library assumes browser environment that supports ```global```. 
One thing to note was that we previously have not encountered this problem, and even though the node packages are of the same version, re-installing them introduced this problem. Would need more investigation into this. 

More details: 
https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

**Closed** 2023-01-16 04:08 UTC
